layout_spectrum: 0.9435076
color:
  saturation: 0.5688058
  lightness: 0.1888461
  brandStrength: 0.7951096
  brandColors:
    - '#1F2027'
    - '#FFFEFF'
    - '#767988'
    - '#9BE1FA'
    - '#885330'
  rhythmicContrast: 0.8185136
typography_spectrum: 0.5152305
name: Bauer Family Travels
